### ISSUE TITLE
Raw ID Fields search

### ISSUE THREAD

**Issue by dangayle** [edoburu/django-any-urlfield#17]
In the docs, it says that the widget should appear just as a regular raw ID field, but it's missing the essential search field. You can see it in the screenshot below, right next to a normal raw id field.

![screen shot 2016-11-21 at 5 57 02 pm](https://cloud.githubusercontent.com/assets/129611/20508086/f4bc4828-b013-11e6-8e06-66ed3f68266e.png)

Thoughts? Solution?

**Comment by vdboor** [comment]
Hmm the raw ID field JavaScript is likely not re-initialized when an inline is added. Please try this with a more recent version of Django, as they improved these things a lot.
